version: '3.8'

services:
  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
    depends_on:
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      - RAILS_ENV=production
    depends_on:
      - redis

  redis:
    image: redis:6.2
