require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/favorite_playlists", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FavoritePlaylist. As you add validations to FavoritePlaylist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FavoritePlaylist.create! valid_attributes
      get favorite_playlists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      favorite_playlist = FavoritePlaylist.create! valid_attributes
      get favorite_playlist_url(favorite_playlist)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_favorite_playlist_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      favorite_playlist = FavoritePlaylist.create! valid_attributes
      get edit_favorite_playlist_url(favorite_playlist)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FavoritePlaylist" do
        expect {
          post favorite_playlists_url, params: { favorite_playlist: valid_attributes }
        }.to change(FavoritePlaylist, :count).by(1)
      end

      it "redirects to the created favorite_playlist" do
        post favorite_playlists_url, params: { favorite_playlist: valid_attributes }
        expect(response).to redirect_to(favorite_playlist_url(FavoritePlaylist.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FavoritePlaylist" do
        expect {
          post favorite_playlists_url, params: { favorite_playlist: invalid_attributes }
        }.to change(FavoritePlaylist, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post favorite_playlists_url, params: { favorite_playlist: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested favorite_playlist" do
        favorite_playlist = FavoritePlaylist.create! valid_attributes
        patch favorite_playlist_url(favorite_playlist), params: { favorite_playlist: new_attributes }
        favorite_playlist.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the favorite_playlist" do
        favorite_playlist = FavoritePlaylist.create! valid_attributes
        patch favorite_playlist_url(favorite_playlist), params: { favorite_playlist: new_attributes }
        favorite_playlist.reload
        expect(response).to redirect_to(favorite_playlist_url(favorite_playlist))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        favorite_playlist = FavoritePlaylist.create! valid_attributes
        patch favorite_playlist_url(favorite_playlist), params: { favorite_playlist: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested favorite_playlist" do
      favorite_playlist = FavoritePlaylist.create! valid_attributes
      expect {
        delete favorite_playlist_url(favorite_playlist)
      }.to change(FavoritePlaylist, :count).by(-1)
    end

    it "redirects to the favorite_playlists list" do
      favorite_playlist = FavoritePlaylist.create! valid_attributes
      delete favorite_playlist_url(favorite_playlist)
      expect(response).to redirect_to(favorite_playlists_url)
    end
  end
end
