deactivate_abandoned_playlists:
  cron: "0 9 * * * America/New_York"   # Runs at 9am daily
  class: "DeactivateAbandonedPlaylistsWorker"

daily_snapshots:
  cron: "0 10 * * * America/New_York"   # Runs at 10am daily
  class: "DailySnapshotWorker"
