name: Deploy to Heroku

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: happy-youtube-watcher
          heroku_email: ${{ github.event.pusher.email }}
      - uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: "CPJ1KQSKX"
          slack-message: |
            **Deploy Status:** ${{ job.status }}

            **Commit:** `[${{ github.event.head_commit.id }}](${{ github.event.head_commit.url }})`
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_API_KEY }}
